version: "2.3"
services:
    postgres:
        image: postgres:10.5
        restart: always
        environment:
            - POSTGRES_USER=store-adm
            - POSTGRES_PASSWORD=pass
            - POSTGRES_DB=store
        ports:
            - "5432:5432"
        volumes: 
            # - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
            # - ./postgres-data:/var/lib/postgresql/data
            # copy the sql script to create tables
            - ./database-script/create_database_store.sql:/docker-entrypoint-initdb.d/create_database_store.sql
            - ./database-script/populate_store.sql:/docker-entrypoint-initdb.d/populate_store.sql
    store:
        image: store-app
        build:
            context: .
            dockerfile: Dockerfile
        container_name: store_api
        depends_on:
            - postgres
        network_mode: host
        # ports:
        #     - "8888:8888"
        volumes:
            - .:/go/src/go-with-compose
        working_dir: /go/src/go-with-compose

volumes:
    database-data: # named volumes can be managed easier using docker-compose